version: '3.2'
services:
      clientdb:
        image: mariadb
        container_name: clientdb
        restart: always
        environment:
          MARIADB_ROOT_PASSWORD: 12345
          MARIADB_USER: admin
          MARIADB_PASSWORD: 12345
          MARIADB_DATABASE: MAIN_SENSOR
        networks: 
          - mynet
        volumes:
          - db-data:/var/lib/mysql
        ports:
          - "3306:3306"
volumes:
  db-data:
networks: 
  mynet:
    driver: bridge
