version: '3.2'
services:
      clientdb:
        image: mariadb
        container_name: clientdb
        restart: always
        environment:
          MARIADB_ROOT_PASSWORD: 12345
          MARIADB_USER: admin
          MARIADB_PASSWORD: 12345
          MARIADB_DATABASE: MAIN_SENSOR
        networks: 
          - mynet
        volumes:
          - db-data:/var/lib/mysql
        ports:
          - "3306:3306"
      appi:
        container_name: roraimacomm     
        build: .
        ports: 
          - "80:80"
        depends_on: 
          - clientdb
        networks: 
          - mynet
        volumes:
          - /dev:/dev
volumes:
  db-data:
networks: 
  mynet:
    driver: bridge
